### ISSUE TITLE
Save Image without spoilers

### ISSUE THREAD

**Issue by disgusdad** [TerraMap/terramap.github.io#15]
More a feature request than an issue, could there be an option for Save Image that would save without revealing spoilers.

**Comment by jasoncoon** [comment]
Yeah, the Windows version supports loading player map files, but the web version does not yet.  I'd like to build a cross platform app version using Electron, which would allow easier loading of world and player map files from the local file system like the Windows version, instead of the user having to browse for them.

**Comment by disgusdad** [comment]
I am currently running the Windows version (1.4.6) and loading a player map file still saves the image with full reveal, is that the expected behavior?
Thank you for the excellent utility.

**Comment by jasoncoon** [comment]
Oh, sorry, this is the issue tracker for the web version.  The windows version is here: https://github.com/TerraMap/windows/issues

I'll double-check when I get a chance.

**Comment by disgusdad** [comment]
sorry, will move issue. Thanks
